// import { Ride } from '../types'

// export const mockRides: Ride[] = [
//   {
//     key: '1',
//     from_location: 'Downto_locationwn Sudbury',
//     to_location: 'Laurentian University',
//     date: '2023-06-15',
//     time: '08:00',
//     price: '5',
//     seats: 3,
//         vehicleInfo: {
//       make: 'to_locationyota',
//       model: 'Corolla',
//       color: 'Silver',
//       picture: null,
//     },
//     ridePreferences: {
//       smoking: false,
//       petFriendly: true,
//       preferredPassengerGender: 'any',
//       maxDeto_locationurDistance: 5,
//     },
//   },
//   {
//     key: '2',
//     from_location: 'New Sudbury Centre',
//     to_location: 'Science North',
//     date: '2023-06-16',
//     time: '10:30',
//     price: '7',
//     seats: 2,
//         vehicleInfo: {
//       make: 'Honda',
//       model: 'Civic',
//       color: 'Blue',
//       picture: null,
//     },
//     ridePreferences: {
//       smoking: false,
//       petFriendly: false,
//       preferredPassengerGender: 'any',
//       maxDeto_locationurDistance: 3,
//     },
//   },
//   {
//     key: '3',
//     from_location: 'Cambrian College',
//     to_location: 'Sudbury Airport',
//     date: '2023-06-17',
//     time: '14:00',
//     price: '15',
//     seats: 4,
//         vehicleInfo: {
//       make: 'Ford',
//       model: 'Escape',
//       color: 'Red',
//       picture: null,
//     },
//     ridePreferences: {
//       smoking: false,
//       petFriendly: true,
//       preferredPassengerGender: 'any',
//       maxDeto_locationurDistance: 10,
//     },
//   },
//   {
//     key: '4',
//     from_location: 'Health Sciences North',
//     to_location: 'Sudbury Arena',
//     date: '2023-06-18',
//     time: '18:30',
//     price: '6',
//     seats: 1,
//         vehicleInfo: {
//       make: 'Chevrolet',
//       model: 'Malibu',
//       color: 'Black',
//       picture: null,
//     },
//     ridePreferences: {
//       smoking: false,
//       petFriendly: false,
//       preferredPassengerGender: 'female',
//       maxDeto_locationurDistance: 2,
//     },
//   },
//   {
//     key: '5',
//     from_location: 'Adanac Ski Hill',
//     to_location: 'Bell Park',
//     date: '2023-06-19',
//     time: '09:15',
//     price: '8',
//     seats: 3,
//         vehicleInfo: {
//       make: 'Nissan',
//       model: 'Rogue',
//       color: 'White',
//       picture: null,
//     },
//     ridePreferences: {
//       smoking: true,
//       petFriendly: true,
//       preferredPassengerGender: 'any',
//       maxDeto_locationurDistance: 7,
//     },
//   },
// ]