import { Ride } from '../types'

export const mockRides: Ride[] = [
  {
    id: '1',
    from: 'Downtown Sudbury',
    to: 'Laurentian University',
    date: '2023-06-15',
    time: '08:00',
    price: '5',
    seats: 3,
    driverId: 'driver1',
    vehicleInfo: {
      make: 'Toyota',
      model: 'Corolla',
      color: 'Silver',
    },
    ridePreferences: {
      smoking: false,
      petFriendly: true,
      preferredPassengerGender: 'any',
      maxDetourDistance: 5,
    },
  },
  {
    id: '2',
    from: 'New Sudbury Centre',
    to: 'Science North',
    date: '2023-06-16',
    time: '10:30',
    price: '7',
    seats: 2,
    driverId: 'driver2',
    vehicleInfo: {
      make: 'Honda',
      model: 'Civic',
      color: 'Blue',
    },
    ridePreferences: {
      smoking: false,
      petFriendly: false,
      preferredPassengerGender: 'any',
      maxDetourDistance: 3,
    },
  },
  {
    id: '3',
    from: 'Cambrian College',
    to: 'Sudbury Airport',
    date: '2023-06-17',
    time: '14:00',
    price: '15',
    seats: 4,
    driverId: 'driver3',
    vehicleInfo: {
      make: 'Ford',
      model: 'Escape',
      color: 'Red',
    },
    ridePreferences: {
      smoking: false,
      petFriendly: true,
      preferredPassengerGender: 'any',
      maxDetourDistance: 10,
    },
  },
  {
    id: '4',
    from: 'Health Sciences North',
    to: 'Sudbury Arena',
    date: '2023-06-18',
    time: '18:30',
    price: '6',
    seats: 1,
    driverId: 'driver4',
    vehicleInfo: {
      make: 'Chevrolet',
      model: 'Malibu',
      color: 'Black',
    },
    ridePreferences: {
      smoking: false,
      petFriendly: false,
      preferredPassengerGender: 'female',
      maxDetourDistance: 2,
    },
  },
  {
    id: '5',
    from: 'Adanac Ski Hill',
    to: 'Bell Park',
    date: '2023-06-19',
    time: '09:15',
    price: '8',
    seats: 3,
    driverId: 'driver5',
    vehicleInfo: {
      make: 'Nissan',
      model: 'Rogue',
      color: 'White',
    },
    ridePreferences: {
      smoking: true,
      petFriendly: true,
      preferredPassengerGender: 'any',
      maxDetourDistance: 7,
    },
  },
]